### ISSUE TITLE
Relationship editor scripts no longer work with VM 2.13.5

### ISSUE THREAD

**Issue by HibiscusKazeneko** [kellnerd/musicbrainz-scripts#33]
If I click on "Edit relationships" on a release, the parser will not appear. This only started today.

I'm running the script through Violentmonkey 2.13.5 on Firefox 108.0.2 on macOS Ventura 13.1.

**Comment by kellnerd** [comment]
Yeah, I can confirm that (same VM, FF 108.0.1). I'm seeing lots of errors in the browser console, a whole lot of other userscripts (which require access to page variables) has also stopped working, probably a general problem with the new VM version.

```
ReferenceError: MB is not defined
```

Might be https://github.com/violentmonkey/violentmonkey/issues/1708, I'll investigate whether that's the issue and we just have to wait for an update or whether I can do something to fix all these scripts.

**Comment by HibiscusKazeneko** [comment]
A Violentmonkey issue sounds extremely plausible. Pretty much every userscript I've tried to use today, regardless of author, has been broken.

**Comment by kellnerd** [comment]
Indeed, Violentmonkey [BETA v2.13.5.2](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.5.2) fixes the issues with all of these scripts for me.

**Comment by kellnerd** [comment]
This should no longer happen with Violentmonkey 2.13.7
