### ISSUE TITLE
Purpose of duplicating Copyright information in the Edit Text

### ISSUE THREAD

**Issue by arsinclair** [kellnerd/musicbrainz-scripts#41]
Hello there!

I come here with a question: in the _parseCopyrightNotice.user.js_ when creating an edit what's the point of duplicating the copyright information in the edit comment itself? It seems redundant to me and I pointed this out in [one of the edits](https://musicbrainz.org/edit/114452738), where the editor directed me here.

I wonder if this information can be dropped from the Edit Comment as this duplication (unless there's a reason for it) just pollutes the database.

Cheers!

**Comment by kellnerd** [comment]
Hi, the purpose is to inform other editors from which text the relationships were derived.
Copyright texts are not always unambiguous and can be mapped to MB relationships exactly, so in case the script makes a wrong guess and the original editor doesn't notice it, future editors still have the chance to correct the relationships.
This wouldn't be possible if the "source" wasn't in the edit note.

**Comment by arsinclair** [comment]
@kellnerd thank you for the information, it makes sense now.
